[package]
name = "briscola"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "=0.5.0-rc.3"
jsonwebtoken = "8"
dotenv = "0.15.0"
